### ISSUE TITLE
Upgrade to 1.18

### ISSUE THREAD

**Issue by r0yzer** [r0yzer/FabricHG#3]
Upgrade everything to 1.18 and use newer version of FabrikMC

**Comment by flerbuster** [comment]
Alternative:

Downgrade everything to 1.8 and use older version of FabrikMC

**Comment by r0yzer** [comment]
ja ok

**Comment by flerbuster** [comment]
1.18 is STill the newest version of minecraft

**Comment by flerbuster** [comment]
this is longer her than this comment
jakob — 23.02.2023 16:45
was ist asbach

**Comment by flerbuster** [comment]
@enricoxD
